// 学習マップ（/map）のデータ定義（SoT）。記事をドメインに束ね、ドメイン間の依存を宣言する。
// 記事タイトルは持たない（collection から slug で引く）。新記事を足したら slugs に1行足すだけ。
// tier は読む順の大きな段（土台→作る→載せる→守る）。deps は前提となるドメイン id。

export type Lang = "ja" | "en";

export const TIERS: ReadonlyArray<{ n: number; ja: string; en: string }> = [
  { n: 1, ja: "土台 — まず世界の仕組みを知る", en: "Foundations — how the world works" },
  { n: 2, ja: "作る — アプリを組み立てる", en: "Build — assembling an app" },
  { n: 3, ja: "載せる — 本番で動かす", en: "Ship — running in production" },
  { n: 4, ja: "守る・回す — 運用と防御", en: "Operate & defend" },
  { n: 5, ja: "見渡す — 事業とマーケの視点", en: "Zoom out — business & marketing view" },
];

export interface Domain {
  id: string;
  tier: number;
  icon: string;
  ja: { label: string; blurb: string };
  en: { label: string; blurb: string };
  deps: string[]; // 前提ドメインの id
  slugs: string[]; // 読む順に並べた記事 slug
}

export const DOMAINS: ReadonlyArray<Domain> = [
  {
    id: "go",
    tier: 1,
    icon: "🐹",
    ja: { label: "Go 言語の基礎", blurb: "並行処理とエラーの扱い。ここが全ての出発点。" },
    en: { label: "Go Language Basics", blurb: "Concurrency and error handling — the starting point." },
    deps: [],
    slugs: ["goroutine-channel-basics", "process-vs-thread", "error-handling-wrapping"],
  },
  {
    id: "os",
    tier: 1,
    icon: "🐧",
    ja: { label: "Linux / OS の土台", blurb: "プロセス・メモリ・権限・シェル。アプリが乗る地面。" },
    en: { label: "Linux / OS Foundations", blurb: "Processes, memory, permissions, shell — the ground apps run on." },
    deps: [],
    slugs: [
      "user-space-vs-kernel-space",
      "physical-and-virtual-memory",
      "kernel-role-for-containers",
      "linux-basic-commands",
      "linux-filesystem-and-permissions",
      "linux-process-and-services",
      "cron-scheduled-jobs",
      "stdin-stdout-stderr",
      "shell-env-and-scripting",
      "linux-distros-and-packages",
    ],
  },
  {
    id: "network",
    tier: 1,
    icon: "🌐",
    ja: { label: "ネットワークの基礎", blurb: "リクエストが届く仕組み。TCP/IP から HTTP・TLS まで。" },
    en: { label: "Networking Basics", blurb: "How a request arrives — from TCP/IP up to HTTP and TLS." },
    deps: [],
    slugs: [
      "how-a-web-request-travels",
      "network-layers-tcpip-osi",
      "tcp-vs-udp",
      "ip-address-and-cidr",
      "ports-and-tcp",
      "dns-basics-and-tools",
      "http-message-anatomy",
      "http-status-codes",
      "http-versions-evolution",
      "https-tls-explained",
      "cookie-session-token",
      "cors-explained",
      "websocket-and-sse",
      "push-notifications",
      "sms-notifications",
      "email-notifications",
      "grpc-vs-rest",
      "protobuf",
      "web-server-proxy-lb-cdn",
      "connection-troubleshooting",
    ],
  },
  {
    id: "database",
    tier: 2,
    icon: "🗄️",
    ja: { label: "データベース", blurb: "壊れない・矛盾しないデータの持ち方。RDBMS と SQL が中心。" },
    en: { label: "Databases", blurb: "Holding data that won't break or contradict — RDBMS and SQL at the core." },
    deps: [],
    slugs: [
      "rdbms-basics",
      "sql-basics",
      "database-schema-design",
      "acid-properties",
      "cap-theorem",
      "caching-cache-aside",
      "soft-delete",
      "db-schema-migration-expand-contract",
    ],
  },
  {
    id: "architecture",
    tier: 2,
    icon: "🏛️",
    ja: { label: "アーキテクチャ / 設計", blurb: "依存の向きを制御し、変更に強い構造を作る。" },
    en: { label: "Architecture / Design", blurb: "Controlling the direction of dependencies for change-resilient structure." },
    deps: ["go", "network"],
    slugs: [
      "why-architecture-and-dip",
      "single-source-of-truth",
      "architecture-patterns-compared",
      "clean-architecture-concepts",
      "clean-architecture-in-go",
      "four-layer-architecture",
      "resource-oriented-design",
      "internal-service-grpc",
      "bff-backend-for-frontend",
    ],
  },
  {
    id: "testing",
    tier: 2,
    icon: "🧪",
    ja: { label: "テスト / QA", blurb: "品質を後付けせず作り込む。ピラミッドで戦略を決める。" },
    en: { label: "Testing / QA", blurb: "Building quality in, not bolting it on — strategy via the pyramid." },
    deps: ["go", "architecture"],
    slugs: ["go-testing-basics", "testing-strategy-pyramid", "qa-quality-built-in", "smoke-testing", "metamorphic-testing", "playwright-e2e", "traffic-replay-and-shadow"],
  },
  {
    id: "payment",
    tier: 2,
    icon: "💳",
    ja: { label: "決済ドメイン（応用例）", blurb: "DB・設計・冪等性が噛み合う実務ドメインの縦串。" },
    en: { label: "Payments (applied example)", blurb: "A real domain where DB, design, and idempotency all meet." },
    deps: ["database", "architecture"],
    slugs: [
      "payment-processing-flow",
      "payment-transaction",
      "idempotency-key-implementation",
      "compensating-transaction",
      "credit-card-payment-mechanism",
      "3d-secure-sca",
      "refund-chargeback-dispute",
      "webhook-implementation",
      "veritrans-payment-gateway",
    ],
  },
  {
    id: "container",
    tier: 3,
    icon: "📦",
    ja: { label: "コンテナ / Docker", blurb: "アプリを箱に詰めてどこでも同じに動かす。" },
    en: { label: "Containers / Docker", blurb: "Boxing an app so it runs the same anywhere." },
    deps: ["os"],
    slugs: [
      "container-namespace-cgroup",
      "docker-big-picture",
      "docker-benefits",
      "dockerfile-basics",
      "image-layers-multistage",
      "container-network-and-data",
      "registry-and-compose",
      "docker-daily-commands",
      "docker-troubleshooting",
    ],
  },
  {
    id: "aws",
    tier: 3,
    icon: "☁️",
    ja: { label: "クラウド / AWS", blurb: "計算・ネットワーク・ストレージをマネージドで借りる。" },
    en: { label: "Cloud / AWS", blurb: "Renting compute, network, and storage as managed services." },
    deps: ["network", "container"],
    slugs: [
      "iaas-paas-saas-caas",
      "aws-basics-for-go",
      "aws-compute-explained",
      "aws-ecr-container-registry",
      "aws-networking-explained",
      "aws-igw-and-subnet-mask",
      "aws-security-groups",
      "aws-data-stores-explained",
      "aws-messaging-explained",
      "aws-security-config-explained",
      "ecs-iam-roles",
      "secure-access-private-resources",
      "aws-ops-explained",
      "snapshots-explained",
    ],
  },
  {
    id: "iac",
    tier: 3,
    icon: "🧱",
    ja: { label: "IaC / Terraform", blurb: "インフラをコードで宣言し、再現可能にする。" },
    en: { label: "IaC / Terraform", blurb: "Declaring infrastructure as code to make it reproducible." },
    deps: ["aws"],
    slugs: ["iac-terraform-basics", "terraform-in-practice", "iac-state-operations", "multi-env-iac", "opentofu-and-terragrunt"],
  },
  {
    id: "cicd",
    tier: 3,
    icon: "🚀",
    ja: { label: "CI/CD・デプロイ・移行", blurb: "ビルドから本番反映まで自動化し、安全に切り替える。" },
    en: { label: "CI/CD, Deploy, Migration", blurb: "Automating build-to-prod and switching over safely." },
    deps: ["container", "aws", "iac"],
    slugs: [
      "deploying-go-apps",
      "cicd-github-actions",
      "asset-pipeline",
      "ci-oidc-keyless-auth",
      "deploy-rollback-strategy",
      "migration-strategy-selection",
      "system-migration-strategy",
      "data-migration",
      "migration-testing",
      "preflight-migrate-validate",
      "api-response-diffing",
    ],
  },
  {
    id: "observability",
    tier: 4,
    icon: "📈",
    ja: { label: "監視 / オブザーバビリティ", blurb: "何を測り、いつ気づき、どこで遅いかを追う。" },
    en: { label: "Monitoring / Observability", blurb: "What to measure, when to notice, and where it's slow." },
    deps: ["os", "aws"],
    slugs: [
      "observability-basics",
      "observe-server-by-hand",
      "what-to-measure-metrics",
      "metric-types-and-collection",
      "metrics-baseline-and-thresholds",
      "traffic-monitoring-signal",
      "build-monitoring-oss",
      "cloudwatch-metrics",
      "cloudwatch-logs",
      "cloudwatch-dashboards",
      "cloudwatch-alarms-and-alerting",
      "distributed-tracing-otel",
      "slo-and-error-budget",
      "symptom-based-troubleshooting",
    ],
  },
  {
    id: "analytics",
    tier: 4,
    icon: "📊",
    ja: { label: "データ分析 / プロダクト分析", blurb: "ユーザーの行動をイベントで測り、どこで抜けるかを見つける。" },
    en: { label: "Data / Product Analytics", blurb: "Measuring user behavior via events and finding where they drop off." },
    deps: ["database"],
    slugs: ["funnel-and-dropoff-analysis", "data-foundation-for-ai", "ai-chatbot-rag-and-bi"],
  },
  {
    id: "business",
    tier: 5,
    icon: "💼",
    ja: { label: "事業・マーケの視点", blurb: "技術から一歩引いて、稼ぎ方・組織文化・見込み客の育て方を経営視点で捉える。" },
    en: { label: "Business & Marketing view", blurb: "Stepping back from tech to see how you make money, org culture, and growing prospects with an executive lens." },
    deps: ["analytics"],
    slugs: ["business-model-for-engineers", "culture-model-for-engineers", "lead-nurturing"],
  },
  {
    id: "security",
    tier: 4,
    icon: "🛡️",
    ja: { label: "セキュリティ（攻撃と防御）", blurb: "代表的な攻撃の仕組みと、境界・鍵・依存での守り方。" },
    en: { label: "Security (attack & defense)", blurb: "How common attacks work, and defending via boundaries, keys, and dependencies." },
    deps: ["network", "database"],
    slugs: [
      "auth-boundary-edge-vs-app",
      "secrets-management",
      "sandboxing",
      "ssh-and-key-auth",
      "sanitization",
      "sql-injection",
      "xss-cross-site-scripting",
      "csrf-attack",
      "command-injection",
      "path-traversal",
      "ssrf-attack",
      "session-hijacking-fixation",
      "credential-stuffing",
      "brute-force-password-spray",
      "privilege-escalation-idor",
      "authentication-bypass",
      "phishing",
      "social-engineering",
      "dns-spoofing",
      "mitm-attack",
      "dos-ddos",
      "port-scanning",
      "dependency-vulnerabilities",
      "supply-chain-attack",
      "zero-day",
      "ransomware",
      "penetration-testing",
    ],
  },
];
